
analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    avoid_print: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
    unnecessary_this: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors_in_immutables: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_build_context_synchronously: ignore
    use_key_in_widget_constructors: ignore
    use_full_hex_values_for_flutter_colors: ignore
    use_setters_to_change_properties: ignore
